# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(895, 664)
        MainWindow.setStyleSheet("*{\n"
"    background-color: #fff;;\n"
"    background: none;\n"
"    color: #000000;\n"
"}\n"
"#menu_widget{\n"
"    background-color: #313a46\n"
"}\n"
"#body_widget{\n"
"    background-color: #313a46\n"
"}\n"
"#menu_widget QPushButton{\n"
"    padding: 10px 10px;\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.menu_widget = QtWidgets.QWidget(self.centralwidget)
        self.menu_widget.setObjectName("menu_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menu_widget)
        self.verticalLayout.setContentsMargins(-1, -1, 9, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Logo_widget = QtWidgets.QHBoxLayout()
        self.Logo_widget.setObjectName("Logo_widget")
        self.label = QtWidgets.QLabel(self.menu_widget)
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setStyleSheet("color: #fff")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Logo_widget.addWidget(self.label)
        self.verticalLayout.addLayout(self.Logo_widget)
        self.btn_home = QtWidgets.QPushButton(self.menu_widget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btn_home.setFont(font)
        self.btn_home.setStyleSheet("color: #fff")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/home/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_home.setIcon(icon)
        self.btn_home.setIconSize(QtCore.QSize(18, 18))
        self.btn_home.setAutoDefault(False)
        self.btn_home.setDefault(True)
        self.btn_home.setObjectName("btn_home")
        self.verticalLayout.addWidget(self.btn_home)
        self.btn_map = QtWidgets.QPushButton(self.menu_widget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btn_map.setFont(font)
        self.btn_map.setStyleSheet("color: #fff")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/map/map.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_map.setIcon(icon1)
        self.btn_map.setIconSize(QtCore.QSize(18, 18))
        self.btn_map.setObjectName("btn_map")
        self.verticalLayout.addWidget(self.btn_map)
        self.btn_more = QtWidgets.QPushButton(self.menu_widget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btn_more.setFont(font)
        self.btn_more.setStyleSheet("color: #fff")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/more_h/more-horizontal.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_more.setIcon(icon2)
        self.btn_more.setIconSize(QtCore.QSize(18, 18))
        self.btn_more.setObjectName("btn_more")
        self.verticalLayout.addWidget(self.btn_more)
        spacerItem = QtWidgets.QSpacerItem(20, 239, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btn_exit = QtWidgets.QPushButton(self.menu_widget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("*{\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    background-color: #941212;\n"
"    color: #fff\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/x_sq/x-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_exit.setIcon(icon3)
        self.btn_exit.setIconSize(QtCore.QSize(18, 18))
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout.addWidget(self.btn_exit)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.menu_widget)
        self.body_widget = QtWidgets.QWidget(self.centralwidget)
        self.body_widget.setObjectName("body_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.body_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.topBar_widget = QtWidgets.QHBoxLayout()
        self.topBar_widget.setContentsMargins(20, 5, -1, 5)
        self.topBar_widget.setObjectName("topBar_widget")
        self.name = QtWidgets.QLabel(self.body_widget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.name.setFont(font)
        self.name.setStyleSheet("color: #fff")
        self.name.setObjectName("name")
        self.topBar_widget.addWidget(self.name)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topBar_widget.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.topBar_widget)
        self.stackwidget = QtWidgets.QStackedWidget(self.body_widget)
        self.stackwidget.setStyleSheet("background-color: #16191d")
        self.stackwidget.setObjectName("stackwidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.gridLayout = QtWidgets.QGridLayout(self.page_home)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.home_scrollArea = QtWidgets.QScrollArea(self.page_home)
        self.home_scrollArea.setStyleSheet("")
        self.home_scrollArea.setWidgetResizable(True)
        self.home_scrollArea.setObjectName("home_scrollArea")
        self.area_home = QtWidgets.QWidget()
        self.area_home.setGeometry(QtCore.QRect(0, 0, 796, 624))
        self.area_home.setObjectName("area_home")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.area_home)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.area_home)
        self.frame.setStyleSheet("background-color: #fff;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 30, 481, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.layoutWidget)
        self.calendarWidget.setStyleSheet("/* Style for header area  ####################################################*/ \n"
"\n"
"QCalendarWidget QWidget {\n"
"     alternate-background-color: #B8E2FF;\n"
"}\n"
"\n"
"/* style for top navigation area ###############################################*/ \n"
"\n"
"#qt_calendar_navigationbar {\n"
"    background-color: #fff;\n"
"    border: 2px solid  #B8E2FF;\n"
"    border-bottom: 0px;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"}\n"
"\n"
"/* style for month change buttons ############################################ */\n"
"\n"
"#qt_calendar_prevmonth, \n"
"#qt_calendar_nextmonth {\n"
"    /* border delete */\n"
"    border: none;  \n"
"    /* delete default icons */\n"
"    qproperty-icon: none; \n"
"    \n"
"    min-width: 13px;\n"
"    max-width: 13px;\n"
"    min-height: 13px;\n"
"    max-height: 13px;\n"
"\n"
"    border-radius: 5px; \n"
"    /* set background transparent */\n"
"    background-color: transparent; \n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* style for pre month button ############################################ */\n"
"\n"
"#qt_calendar_prevmonth {\n"
"    /* set text for button */\n"
"    /*qproperty-text: \">\";*/\n"
"    margin-left:5px;\n"
"    image: url(:/icon/arrow-119-48.ico);\n"
"}\n"
"\n"
"/* style for next month button ########################################### */\n"
"#qt_calendar_nextmonth {\n"
"    margin-right:5px;\n"
"    image: url(:/icon/arrow-19-48.ico);\n"
"    /* qproperty-text: \">\"; */\n"
"}\n"
"#qt_calendar_prevmonth:hover, \n"
"#qt_calendar_nextmonth:hover {\n"
"    background-color: #55aaff;\n"
"}\n"
"\n"
"#qt_calendar_prevmonth:pressed, \n"
"#qt_calendar_nextmonth:pressed {\n"
"    background-color: rgba(235, 235, 235, 100);\n"
"}\n"
"\n"
"\n"
"/* Style for month and yeat buttons #################################### */\n"
"\n"
"#qt_calendar_yearbutton {\n"
"    color: #000;\n"
"    margin:5px;\n"
"    border-radius: 5px;\n"
"    font-size: 13px;\n"
"    padding:0px 10px;\n"
"}\n"
"\n"
" #qt_calendar_monthbutton {\n"
"    width: 110px;\n"
"    color: #000;\n"
"    font-size: 13px;\n"
"    margin:5px 0px;\n"
"    border-radius: 5px;\n"
"    padding:0px 2px;\n"
"}\n"
"\n"
"#qt_calendar_yearbutton:hover, \n"
"#qt_calendar_monthbutton:hover {\n"
"    background-color: #55aaff;\n"
"}\n"
"\n"
"#qt_calendar_yearbutton:pressed, \n"
"#qt_calendar_monthbutton:pressed {\n"
"    background-color: rgba(235, 235, 235, 100);\n"
"}\n"
"\n"
"/* Style for year input lineEdit ######################################*/\n"
"\n"
"#qt_calendar_yearedit {\n"
"    min-width: 53px;\n"
"    color: #000;\n"
"    background: transparent;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* Style for year change buttons ######################################*/\n"
"\n"
"#qt_calendar_yearedit::up-button { \n"
"    image: url(:/icon/arrow-151-48.ico);\n"
"    subcontrol-position: right;\n"
"}\n"
"\n"
"#qt_calendar_yearedit::down-button { \n"
"    image: url(:/icon/arrow-213-48.ico);\n"
"    subcontrol-position: left; \n"
"}\n"
"\n"
"#qt_calendar_yearedit::down-button, \n"
"#qt_calendar_yearedit::up-button {\n"
"    width:10px;\n"
"    padding: 0px 5px;\n"
"    border-radius:3px;\n"
"}\n"
"\n"
"#qt_calendar_yearedit::down-button:hover, \n"
"#qt_calendar_yearedit::up-button:hover {\n"
"    background-color: #55aaff;\n"
"}\n"
"\n"
"/* Style for month select menu ##################################### */\n"
"\n"
"#calendarWidget QToolButton QMenu {\n"
"     background-color: white;\n"
"\n"
"}\n"
"#calendarWidget QToolButton QMenu::item {\n"
"    /*padding: 10px;*/\n"
"}\n"
" #calendarWidget QToolButton QMenu::item:selected:enabled {\n"
"    background-color: #55aaff;\n"
"}\n"
"\n"
"#calendarWidget QToolButton::menu-indicator {\n"
"    /* Remove toolButton arrow */\n"
"      /*image: none; */\n"
"    nosubcontrol-origin: margin;\n"
"    subcontrol-position: right center;\n"
"    margin-top: 10px;\n"
"    width:20px;\n"
"}\n"
"\n"
"/* Style for calendar table ########################################## */\n"
"#qt_calendar_calendarview {\n"
"    /* Remove the selected dashed box */\n"
"    outline: 0px;\n"
"\n"
"    border: 2px solid  #B8E2FF;\n"
"    border-top: 0px;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"#qt_calendar_calendarview::item:hover {\n"
"   border-radius:5px;\n"
"    background-color:#000000;\n"
"}\n"
"\n"
"#qt_calendar_calendarview::item:selected {\n"
"    background-color: #55aa7f; \n"
"    border-radius:5px;\n"
"}\n"
"")
        self.calendarWidget.setObjectName("calendarWidget")
        self.horizontalLayout_2.addWidget(self.calendarWidget)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.selectedDate_lbl = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.selectedDate_lbl.setFont(font)
        self.selectedDate_lbl.setObjectName("selectedDate_lbl")
        self.verticalLayout_5.addWidget(self.selectedDate_lbl)
        self.selectedDate_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.selectedDate_lineEdit.setStyleSheet("")
        self.selectedDate_lineEdit.setObjectName("selectedDate_lineEdit")
        self.verticalLayout_5.addWidget(self.selectedDate_lineEdit)
        self.information_lbl = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.information_lbl.setFont(font)
        self.information_lbl.setObjectName("information_lbl")
        self.verticalLayout_5.addWidget(self.information_lbl)
        self.infomation_textEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.infomation_textEdit.setObjectName("infomation_textEdit")
        self.verticalLayout_5.addWidget(self.infomation_textEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_4.addWidget(self.frame)
        self.home_scrollArea.setWidget(self.area_home)
        self.gridLayout.addWidget(self.home_scrollArea, 0, 0, 1, 1)
        self.stackwidget.addWidget(self.page_home)
        self.page_more = QtWidgets.QWidget()
        self.page_more.setObjectName("page_more")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_more)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.more_scrollArea = QtWidgets.QScrollArea(self.page_more)
        self.more_scrollArea.setWidgetResizable(True)
        self.more_scrollArea.setObjectName("more_scrollArea")
        self.area_more = QtWidgets.QWidget()
        self.area_more.setGeometry(QtCore.QRect(0, 0, 796, 624))
        self.area_more.setObjectName("area_more")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.area_more)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_2 = QtWidgets.QFrame(self.area_more)
        self.frame_2.setStyleSheet("background-color: #fff;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_8.addWidget(self.frame_2)
        self.more_scrollArea.setWidget(self.area_more)
        self.gridLayout_3.addWidget(self.more_scrollArea, 0, 0, 1, 1)
        self.stackwidget.addWidget(self.page_more)
        self.page_map = QtWidgets.QWidget()
        self.page_map.setObjectName("page_map")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_map)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.map_scrollArea = QtWidgets.QScrollArea(self.page_map)
        self.map_scrollArea.setWidgetResizable(True)
        self.map_scrollArea.setObjectName("map_scrollArea")
        self.area_map = QtWidgets.QWidget()
        self.area_map.setGeometry(QtCore.QRect(0, 0, 796, 624))
        self.area_map.setObjectName("area_map")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.area_map)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_3 = QtWidgets.QFrame(self.area_map)
        self.frame_3.setStyleSheet("background-color: #fff;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6.addWidget(self.frame_3)
        self.map_scrollArea.setWidget(self.area_map)
        self.gridLayout_2.addWidget(self.map_scrollArea, 0, 0, 1, 1)
        self.stackwidget.addWidget(self.page_map)
        self.verticalLayout_2.addWidget(self.stackwidget)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.body_widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackwidget.setCurrentIndex(0)
        self.btn_exit.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "LMS"))
        self.btn_home.setText(_translate("MainWindow", " Home"))
        self.btn_map.setText(_translate("MainWindow", " Map"))
        self.btn_more.setText(_translate("MainWindow", " More"))
        self.btn_exit.setText(_translate("MainWindow", " Exit"))
        self.name.setText(_translate("MainWindow", "Live Monitering System"))
        self.selectedDate_lbl.setText(_translate("MainWindow", "Selected Date"))
        self.selectedDate_lineEdit.setText(_translate("MainWindow", "yyyy-MM-dd"))
        self.information_lbl.setText(_translate("MainWindow", "Infomation"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
